#!/bin/bash

# This script will create a list of packages in pkgs.txt


packages=("kakoune" "tmux")

# The following for loop will write each package to pkgs.txt file.
echo "Creating pkgs.txt with the following packages:"
for package in "${packages[@]}"; do
    echo "$package" >> pkgs.txt
    echo "-$package"
done

echo "Package list saved to pkgs.txt file"
