#!/bin/bash
# This script sets up symbolic links for configuration files.

# Function to set up symbolic links
symlinks() {
    # Path to the directory that contains the configuration files
    CONFIG_PATH="./configs"

    # Create the ~/bin directory if it doesn’t exist and link the scripts
    mkdir -p ~/bin
    ln -sf "$CONFIG_PATH/bin/sayhi" ~/bin/sayhi
    ln -sf "$CONFIG_PATH/bin/install-fonts" ~/bin/install-fonts

    # Set up Kakoune and Tmux configuration links in ~/.config
    mkdir -p ~/.config/kak
    ln -sf "$CONFIG_PATH/config/kak/kakrc" ~/.config/kak/kakrc
    mkdir -p ~/.config/tmux
    ln -sf "$CONFIG_PATH/config/tmux/tmux.conf" ~/.config/tmux/tmux.conf

    # Link the custom bashrc to ~/.bashrc
    ln -sf "$CONFIG_PATH/home/bashrc" ~/.bashrc

    # Print a confirmation message to the user
    echo "Symbolic links for configuration files have been successfully set up."
}

# this Calls the function from the top to create the symbolic links
symlinks

