#!/bin/bash
# Script to add a new user with optional shell and groups

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

# Show usage information
usage() {
    echo "Usage: $0 -u USERNAME [-s SHELL] [-g GROUPS]"
    echo "  -u   Username (required)"
    echo "  -s   User's login shell (default: /bin/bash)"
    echo "  -g   Comma-separated list of additional groups"
    exit 1
}

# Parse options
while getopts "u:s:g:" opt; do
    case "$opt" in
        u) username=$OPTARG ;;
        s) shell=$OPTARG ;;
        g) groups=$OPTARG ;;
        *) usage ;;
    esac
done

# Check if username is provided
if [[ -z "$username" ]]; then
    echo "Error: Username is required."
    usage
fi

# Set default shell if none specified
shell=${shell:-/bin/bash}

# Create the user with specified shell and groups
echo "Creating user '$username'..."
if useradd -m -s "$shell" ${groups:+-G "$groups"} "$username"; then
    echo "User '$username' created successfully."

    # Set user password
    echo "Please set a password for '$username':"
    passwd "$username"

    # Copy default files to user's home directory
    cp -r /etc/skel/. "/home/$username"
    chown -R "$username:$username" "/home/$username"
    echo "Home directory set up for '$username'."
else
    echo "Error: Could not create user '$username'."
    exit 1
fi
